defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: "/:title.html"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
exclude:
  ["andk-jekyll.sublime-project","andk-jekyll.sublime-workspace"]
collections:
  category:
    output: true