defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
exclude:
  ["andk-jekyll.sublime-project","andk-jekyll.sublime-workspace"]